spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 12345.com
    url: jdbc:postgresql://localhost:5432/students
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
